### ISSUE TITLE
Paint problem

### ISSUE THREAD

**Issue by ghost** [lopste/drawing-station#2]
When i speed up and draw with my mouse moving really fast, you can see the paint starts to be some dots separated. Is it possible to fix that so when you draw fast the paint dots don't try to separate.

**Comment by vercte** [comment]
That’s all going to be fixed in the next version, which is coming fairly
soon (uses lines instead of circles)

**Comment by vercte** [comment]
I just merged v1.0, try it out! This bug is fixed.
